adding OSR implementation
umangm/rapid pull request #6
Opened 2024-05-11 07:20 UTC by zhengshi1998

The implementation of OSR algorithm has been added to the reporsitory. The detail of this algorithm can be found via https://dl.acm.org/doi/10.1145/3597503.3639099.

2024-05-11 13:32 UTC, umangm requested changes
Please address my comments

2024-05-11 13:32 UTC, umangm commented on generateMetaInfo.py
Is this file required? Does OSR not run on the same formats as other dynamic analysis algorithms in RAPID?

2024-05-11 13:32 UTC, umangm commented on rapid.iml
Remove and adjust the dependencies in `rapid.xml` instead

2024-05-11 13:32 UTC, umangm commented on rapid1.iml
Remove and adjust the dependencies in `rapid.xml` instead

2024-05-11 13:32 UTC, umangm commented on src/OSR.java
Can you please structure this file like other files (See for example `src/SyncPreserving.java`)?

2024-05-11 13:32 UTC, umangm commented on src/engine/racedetectionengine/OSR/POBuild/NumArrayMin.java
Looks like `POBuild` is a standalone datastructure. If so, can it go to the `util` package of `rapid`?

2024-05-11 13:32 UTC, umangm commented on src/engine/racedetectionengine/OSR/POBuild/NumArrayMin.java
> +//			System.out.println("right : " + left + ", " + right + ", " + mid);
```suggestion

```

2024-05-11 13:32 UTC, umangm commented on src/engine/racedetectionengine/OSR/POBuild/NumArrayMin.java
> +//			System.out.println("left : " + left + ", " + right + ", " + mid);
```suggestion
```

2024-05-11 13:32 UTC, umangm commented on src/engine/racedetectionengine/OSR/POBuild/NumArrayMin.java
> +//		this.printArray();
```suggestion
```

2024-05-11 13:32 UTC, umangm commented on src/engine/racedetectionengine/OSR/POBuild/NumArrayMin.java
> +//		System.out.println("query : " + left + ", " + right);
```suggestion
```

2024-05-11 13:32 UTC, umangm commented on src/engine/racedetectionengine/OSR/OSREvent.java
> +//                    System.out.println("add edge : " + curNode.third + " -> " + testNode.third);
```suggestion
```

2024-05-11 13:32 UTC, umangm commented on src/engine/racedetectionengine/OSR/OSREvent.java
> +//        System.out.println(nodes);
```suggestion
```

2024-05-11 13:32 UTC, umangm commented on src/engine/racedetectionengine/OSR/OSREvent.java
> +        // backwardEdge = <lockId, acqO, thId of acqO>
```suggestion
```

2024-05-11 13:32 UTC, umangm commented on src/engine/racedetectionengine/OSR/OSREvent.java
> +//        }
```suggestion
```

2024-05-11 13:32 UTC, umangm commented on src/engine/racedetectionengine/OSR/OSREvent.java
> +//                    System.out.println("OSR set between " + e1.auxId + ", " + e2.auxId + " " + state.osrEventSet);
```suggestion
```

2024-05-11 13:32 UTC, umangm commented on src/engine/racedetectionengine/OSR/OSREvent.java
> +//                    System.out.println("OSR set between " + e1.auxId + ", " + e2.auxId + " " + state.osrEventSet);
```suggestion
```

2024-05-11 13:32 UTC, umangm commented on src/OSR.java
> +//        po.printArray();
```suggestion
```

2024-05-11 13:32 UTC, umangm commented on src/rapid.iml
This file can be deleted

2024-05-11 13:32 UTC, umangm commented on src/util/NeibhorsHardCodeWordTricks.java
Why was this deleted?

2024-05-11 13:32 UTC, umangm commented on src/util/PairHardCodeWordTricks.java
Why was this deleted?

2024-05-13 15:22 UTC, zhengshi1998 commented on generateMetaInfo.py
This is requried, OSR needs some meta information to init data structures. This python file scans the trace once and produce the number of threads, locks, variables, total number of events and number of events per thread.

2024-09-25 02:13 UTC, zhengshi1998 commented
I have addressed these comments, please check now.

2024-09-25 05:23 UTC, umangm commented
Optimistic Sync Reversal Races from ICSE’24

2024-09-25 05:24 UTC, merged